# This is a basic workflow that is manually triggered

name: Run Specific Test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      test_script_path:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Test Script Path'
        # Default value if no value is explicitly provided
        default: './scripts/k6/rest-api/scoresapi-team-match-list/scores-team-match-list-test.js'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
      duration:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Duration ex:10m,15m,5m'
        # Default value if no value is explicitly provided
        default: '10m,15m,5m'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
      target:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Target ex:20,30,0'
        # Default value if no value is explicitly provided
        default: '1,1,0'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  k6_cloud_test:
    name: k6 cloud test run
    runs-on: generic
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Run k6 cloud test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: '${{inputs.test_script_path}} -e DURATION=${{inputs.duration}} -e TARGET=${{inputs.target}}'
          cloud: true
          token: '***********************'
